In [4]:
import pandas as pd

# 成绩清单
df = pd.DataFrame([
    {"姓名": "张三","语文成绩": 90,"数学成绩": 80,"英语成绩": 70},
    {"姓名": "李四","语文成绩": 80,"数学成绩": 90,"英语成绩": 80},
    {"姓名": "王五","语文成绩": 70,"数学成绩": 80,"英语成绩": 90},
    {"姓名": "赵六","语文成绩": 60,"数学成绩": 70,"英语成绩": 80},
    {"姓名": "孙七","语文成绩": 80,"数学成绩": 90,"英语成绩": 70},
    {"姓名": "周八","语文成绩": 90,"数学成绩": 80,"英语成绩": 60},
    {"姓名": "吴九","语文成绩": 80,"数学成绩": 70,"英语成绩": 90},
    {"姓名": "郑十","语文成绩": 70,"数学成绩": 80,"英语成绩": 80},
    {"姓名": "王十一","语文成绩": 80,"数学成绩": 90,"英语成绩": 90},
    {"姓名": "张十二","语文成绩": 90,"数学成绩": 80,"英语成绩": 70}
])

df

    姓名  语文成绩  数学成绩  英语成绩
0   张三    90    80    70
1   李四    80    90    80
2   王五    70    80    90
3   赵六    60    70    80
4   孙七    80    90    70
5   周八    90    80    60
6   吴九    80    70    90
7   郑十    70    80    80
8  王十一    80    90    90
9  张十二    90    80    70

In [8]:
# 统计计算
int(df["语文成绩"].max()), int(df["语文成绩"].min()),int(df["语文成绩"].mean ()),int(df["语文成绩"].sum ())

(90, 60, 79, 790)

In [10]:
df.columns.tolist()

['姓名', '语文成绩', '数学成绩', '英语成绩']

In [12]:
df.values.tolist()

[['张三', 90, 80, 70],
 ['李四', 80, 90, 80],
 ['王五', 70, 80, 90],
 ['赵六', 60, 70, 80],
 ['孙七', 80, 90, 70],
 ['周八', 90, 80, 60],
 ['吴九', 80, 70, 90],
 ['郑十', 70, 80, 80],
 ['王十一', 80, 90, 90],
 ['张十二', 90, 80, 70]]

In [14]:
df.index.tolist()

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [16]:
df.shape

(10, 4)

In [18]:
df.size

40

In [20]:
df.describe()

            语文成绩       数学成绩       英语成绩
count  10.000000  10.000000  10.000000
mean   79.000000  81.000000  78.000000
std     9.944289   7.378648  10.327956
min    60.000000  70.000000  60.000000
25%    72.500000  80.000000  70.000000
50%    80.000000  80.000000  80.000000
75%    87.500000  87.500000  87.500000
max    90.000000  90.000000  90.000000

In [21]:
df.dtypes

姓名      object
语文成绩     int64
数学成绩     int64
英语成绩     int64
dtype: object