In [37]:
import pandas as pd

# 读取数据
df = pd.read_csv("./Data/sales.csv",usecols=['订单号','产品名称','产品类别','单价','销售数量'],index_col='订单号')

df['销售额'] = df['单价'] * df['销售数量']

df.to_csv("./Data/sales_result.csv",index=False)

df.head(10)
df.tail(10)
df.describe()
df.info
# 一个中括号取一个列
df['产品名称']  
# 两个中括号取多个列
df[['产品名称','单价']]

            产品名称   单价
订单号
6805677496    枕头  199
5857234132    海苔   29
5888085059  智能音箱  399
6823473137    面包   29
6801664364    薯片   19
...          ...  ...
5887473055    小说   49
5808511756    坚果   79
5811169466    围巾  129
6876456690    果汁   39
6842608338    蜂蜜   89

[1000 rows x 2 columns]

In [38]:
# 选择行iloc, loc
# 示例:df.iloc[start:end:step,start:end:step] 表示: 开始:结束:步长
# iloc基于行号进行选择
df.iloc[0:100:2]

# 基于索引进行选择
df.loc[6805677496:5852807025:2]

            产品类别  产品名称  销售数量   单价   销售额
订单号
6805677496  家居用品    枕头    10  199  1990
5888085059  电子产品  智能音箱     5  399  1995
6801664364    食品    薯片     2   19    38
6857752388    服装    袜子     7  -29  -203
5875402232  电子产品   路由器     9  299  2691
5808071569    食品   矿泉水     9   29   261
5891597362  电子产品    鼠标     3   89   267
5804178086  电子产品  蓝牙耳机    10  199  1990
5812573980    食品    坚果     2   79   158
5852698441  家居用品    蜡烛     6   49   294

In [48]:
# 获取产品类别是食品或服装的
df[df['产品类别'].isin(['食品','服装'])]
# 获取销售数量大于10的且单价大于400的
df[(df['销售数量'] >= 10) & (df['单价'] >= 400)]

            产品类别   产品名称  销售数量    单价    销售额
订单号
5883051305  电子产品   智能手机    10  2999  29990
5814938951  电子产品   平板电脑    10  2499  24990
6890609921  电子产品  笔记本电脑    10  5999  59990
5878122717  电子产品   智能手表    10   899   8990
6849785580  电子产品  笔记本电脑    10  5999  59990
5855105517  电子产品    显示器    10  1299  12990
5830301956    服装     风衣    10   699   6990
5823245607  电子产品   智能手机    10  2999  29990
5851751960    服装     外套    10   599   5990
6846830553  电子产品    显示器    10  1299  12990
5842022688  电子产品    显示器    10  1299  12990
6899012557    服装    西装裤    10   449   4490
5800711405    服装    羽绒服    10   899   8990