In [6]:
import pandas as pd

df = pd.read_csv("./Data/sales.csv",nrows=10)

# 数据排序, 默认升序,ascending=True表示升序,False表示降序
df.sort_values('单价',ascending=True)
df.sort_values(['单价','销售数量'],ascending=[True,False])

          订单号  产品类别  产品名称  销售数量   单价 客户所在城市  支付方式        订单日期
6  6857752388    服装    袜子     7  -29     郑州    现金  2025-06-02
4  6801664364    食品    薯片     2   19    NaN  微信支付  2025/06/02
1  5857234132    食品    海苔     5   29     天津    现金  2025-06-01
5  5897064217    图书    字帖     4   29     广州    现金  2025-06-02
3  6823473137    食品    面包     3   29     北京   银行卡  2025-06-02
9  5888085059    图书    字典     2   99     青岛  微信支付  2025-06-04
0  6805677496  家居用品    枕头    10  199     合肥   支付宝  2025-06-01
7  6898807429    服装    T恤     6  199     武汉   银行卡  2025-06-02
8  5875402232  电子产品   路由器     9  299     福州   银行卡  2025-06-03
2  5888085059  电子产品  智能音箱     5  399     福州  微信支付  2025-06-01

In [36]:
df = pd.read_csv("./Data/sales.csv",nrows=20)
df['销售金额'] = df['单价'] * df['销售数量']
# 分组
# 3.1 根据 产品类别 分组，统计各个类别的 订单数量
df.groupby('产品类别')['订单号'].count()
# 3.2 根据 产品类别 分组，统计各个类别的 销售数量 之和
df.groupby('产品类别')['销售数量'].sum()
# 3.3 根据 产品类别 分组，统计各个类别的 销售金额 之和
df.groupby('产品类别')['销售金额'].sum()
# 3.4 根据 产品类别 分组，统计各个类别的最低商品 单价
df.groupby('产品类别')['单价'].min()
# 3.5 根据 产品类别 分组，统计各个类别的最高商品 单价
df.groupby('产品类别')['单价'].max()
# 3.6 根据 产品类别 分组，统计各个类别的平均商品 单价
df.groupby('产品类别')['单价'].mean()
# 3.7 根据 产品类别 分组，统计各个类别的 平均单价、最高单价、最低单价
df.groupby('产品类别')['单价'].agg(['mean','max','min'])
# 3.8 根据 产品类别 分组，统计各个类别的:销售数量之和、销售金额之和、平均单价
df.groupby('产品类别').agg({'销售数量':'sum','销售金额':'sum','单价':'mean'})

      销售数量  销售金额          单价
产品类别
图书      25  1115   51.000000
家居用品    26  4274  149.000000
服装      23  4981  189.666667
电子产品    27  6943  246.500000
食品      21   689   37.000000